# Generated by Django 5.0 on 2023-12-05 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerapi', '0003_rename_interestvolunteers_interestedvolunteers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerusers',
            name='volunteer_username',
        ),
    ]
