# Generated by Django 5.0 on 2023-12-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerapi', '0005_alter_jobposts_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerusers',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
