# Generated by Django 5.0 on 2023-12-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerapi', '0006_alter_volunteerusers_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerusers',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
